### PR TITLE
`where` for `ActiveResource::Collection`

### PR DESCRIPTION
**Pull request by om-nishu-trantor**
Add `where` to activeresource collection.
In activerecord you can call `where` on `ActiveRecord::Collection`, kind
of similar functionality for activeresource.

```
resources  = ActiveresourceClass.where(column_a: 'a')
resources.where(column_b: 'b') #should call resources with `column_a=a&column_b=b`, currently does not works
```

### CODE REVIEW

**Comment by RajRoR** [comment]
Yah, simple but a must have feature. :+1: @om-nishu-trantor

**Comment by om-nishu-trantor** [comment]
@arthurnn Any thoughts on this one... Sry to bother you as I found u as a collaborator who can look into it. Can u please help merging this or letting me know any improvements as I am currently using this feature in an enterprise app I am working on and source in gemfile is pointing to my forked repo, I want to point it back to activeresource if it could be merged then I would be having an independent app relying on rails original activeresource repo and not a forked one.

**Comment by dgilperez** [comment]
+1 !

**Comment by abhayshukla87** [comment]
:+1:

**Comment by amita-trantor** [comment]
:+1:

**Comment by andvikram** [comment]
:+1:

**Comment by arthurnn** [comment]
I am not sure about this new API to be honest with you. code-wise look ok, but would like to know what @rafaelfranca things about the API itself.
thanks for the PR

**Comment by om-nishu-trantor** [comment]
@rafaelfranca , Any updates over this feature/api yet ?

**Comment by om-nishu-trantor** [comment]
@rafaelfranca and @arthurnn . Can you please update on the progress as it is long time this PR is unattended.

**Pull request merged**
