### PR TITLE
Adding Inch-CI badge

### PR DESCRIPTION
**Pull request by SweeD**
With this PR i would like to add [Inch-CI](http://inch-ci.org/) to Active Resource. 

You can find the detailed page for Active Resource [here](http://inch-ci.org/github/rails/activeresource/branch/master)

In case we decide to use this, we would just need to add a webhook to the project, like described here:
http://inch-ci.org/help/webhook

What do you guys think of continuous checking for good inline documentation, as well?

/cc @rafaelfranca

### CODE REVIEW

**Comment by rrrene** [comment]
Hi everybody! I'm the maintainer of [Inch](http://github.com/rrrene/inch) and [Inch CI](https://github.com/inch-ci/inch_ci-web). 

If you have any questions about this, I am more than happy to assist! :+1:

**Comment by SweeD** [comment]
@rafaelfranca would be awesome to hear (read in fact^^) your thoughts about this? :smile:

**Comment by rafaelfranca** [comment]
I'll defer this decision to the @rails/documentation team. I'm fine with it in this repo but they may want to use it in rails/rails too.

**Comment by vijaydev** [comment]
Looks neat! +1 for adding in rails/rails.

**Pull request merged**
