### PR TITLE
Use a custom deprecator instead of ActiveSupport::Deprecation directly

### PR DESCRIPTION
**Pull request by adrian-gomez**
This will address some errors we are getting while trying to update to rails 7.2

### CODE REVIEW

**Comment by adrian-gomez** [comment]
@byroot Is there anything I can do to get this merged? Right now active resource it's not compatible with rails 7.2 if you have any deprecation warnings.

**Comment by nerdrew** [comment]
Is this going to be released soon?

**Comment by jeremy** [comment]
App deprecators were added in Rails 7.1. This PR breaks Rails 6.1 and 7.0 support.

**Comment by byroot** [comment]
@jeremy do you have a repro or even just a error+backtrace? Because this OR checks for the Rails version, and 6.1 and 7.0 are tested on CI.

**Comment by byroot** [comment]
Hum, I see: https://github.com/rails/activeresource/issues/406

**Pull request closed without merging**
